### ISSUE TITLE
对更新版的YouTube和YouTube music失去了作用

### ISSUE THREAD

**Issue by Biaogo** [Xposed-Modules-Repo/com.wovow.youtubehelper#1]
在新版本YouTube 去了广告但是还有广告，主页广告那个框是没掉了

**Comment by ohyeah521** [comment]
谷歌的应用中有10%以上的代码都是在琢磨怎么展示广告，已经patch了几十处影响观看视频的广告代码，不影响视频观看的代码不打算管了，实在是太累了，更新太频繁，每个版本广告代码都在变化。
