### ISSUE TITLE
Can we expect any updates now that Vanced is taken down?

### ISSUE THREAD

**Issue by shantanub08** [Xposed-Modules-Repo/com.wovow.youtubehelper#2]
I believe bringing back YT Vanced as Xposed module is the best way to bring it back. Although it might leave out non-root users, at least the development can restart under different name

**Comment by ohyeah521** [comment]
Version 8.0.0 has been released on the store, supporting YouTube version 17.14.35 to advertise and play in the background;
Support YouTube Music 5.02.50 version to advertise, background playback;
Supports all versions of Twitter to go to advertising
