### ISSUE TITLE
Module not working 

### ISSUE THREAD

**Issue by abdrau26** [Xposed-Modules-Repo/com.wovow.youtubehelper#3]
I have installed this module but it is not working. It does not disable ads. Here are the details:
LSPosed apk framework using magisk zygisk
Youtube version:16.41.35

API version
93

Injection Interface
Zygisk

Dex Optimizer Wrapper
Supported

Framework version
1.8.3 (6552)

Manager version
1.8.3 (6552)

System version
11 (API 30)

Device
Xiaomi Redmi 2201116TG 

System ABI
arm64-v8a

**Comment by ohyeah521** [comment]
Support YouTube version 17.14.35 to advertise and play in the background
Support YouTube music version 5.02.50 to advertise and play in the background
Support all versions of Twitter to advertise
