### ISSUE TITLE
Thank you for the update

### ISSUE THREAD

**Issue by SHRoot92** [Xposed-Modules-Repo/com.wovow.youtubehelper#8]
Hi,

Thank you for the update as it was really needed and hope that you add support for YT 19.36.xx soon as that version seems to have broken BG playback for most root users.

Thank you so much for your continuous hard work.

BTW i sent an email to you few days back could you please check it.

Thanks in advance.

**Comment by ohyeah521** [comment]
I didn't receive the email

**Comment by SHRoot92** [comment]
Your email id is ohyeah521@gmail.com right ?

**Comment by SHRoot92** [comment]
Mail sent already 6 days ago but I resend it today

**Comment by ohyeah521** [comment]
I found it in my spam and I replied to you yesterday.

**Comment by SHRoot92** [comment]
Hi please check your mail once i already made donation
